---


title: "GC DATA SCIENCE - NOVEMBER 6 LAB "


author: "XXXXXXXXXXX"


date: "mm/dd/2023"

output: pdf_document



---


```{r setup, include=FALSE}


knitr::opts_chunk$set(echo = TRUE,fig.height = 9 ,fig.width = 11)




```



```{r include = FALSE, warning = FALSE, results = FALSE}


library(tidyverse)
library(openintro)
library(tinytex)



# we also will insert any data frames that need to be read
# so that the data we use in the console can also used when we knit



load(url("https://github.com/mdschochgc/GCTest/blob/main/data/ames.rda?raw=true"))

source("https://raw.githubusercontent.com/mdschochgc/GCTest/main/data/gcdot_plot.r")
ames <- filter(ames, Gr.Liv.Area < 4000 )




```


# This is empty white space 





```{r "TEST", error = TRUE, warning = FALSE}


# insert your R commands on the next lines

dim(ames)























```



# Start Your Analysis below
















