---



title: "GC DATA SCIENCE - OCTOBER 11  LAB "







author: "XXXXXXXXXXX"





date: "mm/dd/2023"





output: pdf_document







---





```{r setup, include=FALSE}



knitr::opts_chunk$set(echo = TRUE,fig.height = 9 ,fig.width = 11)






```



## R Markdown




```{r include = FALSE, warning = FALSE, results = FALSE}

library(tidyverse)

library(openintro)

library(tinytex)


# we also will insert any data frames that need to be read
# so that the data we use in the console can also used when we knit



load(url("https://github.com/mdschochgc/GCTest/blob/main/data/Oct02.rda?raw=true"))
source("https://raw.githubusercontent.com/mdschochgc/GCTest/main/data/gcdot_plot.r")




```





# This is empty white space 







```{r "TEST", error = TRUE, warning = FALSE}



# insert your R commands on the next lines


















```

# Start Your Analysis below













